on:
    push:
        branches:
            - main
name: Milestone Closure
jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Upload md files to Wiki
      uses: docker://decathlon/wiki-page-creator-action:latest
      env:
        ACTION_MAIL: 26373373+alwynmathew@users.noreply.github.com
        ACTION_NAME: alwynmathew
        GH_PAT: ${{ secrets.GH_PAT }}
        MD_FOLDER: wiki
        OWNER: BIM2TWIN-Team
        REPO_NAME: DTP_API
        SKIP_MD: README.md